services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: ujjwal
      POSTGRES_PASSWORD: ujjwal
      PGDATA: /data/postgres
      TZ: UTC


    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - microservices-network
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      TZ: UTC

    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-network
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ujjwal
      MONGO_INITDB_ROOT_PASSWORD: ujjwal
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    networks:
      microservices-network:
        aliases:
            - mongo
            - mongodb

    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ujjwal
      ME_CONFIG_MONGODB_ADMINPASSWORD: ujjwal
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - microservices-network
    ports:
      - 8081:8081
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025




networks:
  microservices-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
